In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, classification_report
from sklearn.preprocessing import StandardScaler
import scipy.stats

%matplotlib inline

In [2]:
train_df = pd.read_csv('../dataset/train.csv')
val_df = pd.read_csv('../dataset/val.csv')
test_df = pd.read_csv('../dataset/test.csv')

In [3]:
train_df.describe().T

count          mean           std        min           25%  \
ID   113842.0  1.420255e+05  82248.545392   3.000000  70796.750000   
V1   113842.0  1.972910e-04      1.951060 -56.407510     -0.923479   
V2   113842.0  1.288795e-03      1.651064 -72.715728     -0.595602   
V3   113842.0  9.717363e-03      1.496916 -32.454198     -0.883877   
V4   113842.0 -4.169208e-03      1.412633  -5.600607     -0.853728   
V5   113842.0  4.749962e-04      1.367533 -42.147898     -0.689853   
V6   113842.0  5.141158e-03      1.330583 -26.160506     -0.766094   
V7   113842.0  5.769024e-03      1.204111 -41.506796     -0.552071   
V8   113842.0 -2.450588e-03      1.185504 -50.943369     -0.209492   
V9   113842.0 -2.107069e-03      1.095415 -13.434066     -0.647477   
V10  113842.0  5.209413e-03      1.071337 -24.403185     -0.533477   
V11  113842.0 -1.686401e-03      1.014689  -4.682931     -0.763105   
V12  113842.0  3.944337e-03      0.977039 -18.553697     -0.402650   
V13  113842.0  2.043291e-03      0.994908  -3.844974     -0.647334   
V14  113842.0  4.397323e-03      0.933753 -15.623187     -0.423962   
V15  113842.0 -5.004147e-04      0.915666  -4.152532     -0.584307   
V16  113842.0  2.905432e-03      0.864903 -13.303888     -0.467574   
V17  113842.0  3.397329e-03      0.808552 -21.297906     -0.486154   
V18  113842.0  1.114402e-03      0.830763  -8.668815     -0.497362   
V19  113842.0  3.000598e-04      0.814542  -4.932733     -0.456712   
V20  113842.0 -4.995680e-04      0.763326 -28.009635     -0.211935   
V21  113842.0 -1.242469e-03      0.722001 -22.757540     -0.229710   
V22  113842.0  4.088347e-07      0.723829  -8.887017     -0.540266   
V23  113842.0 -1.317418e-03      0.636061 -44.807735     -0.162180   
V24  113842.0 -8.841494e-04      0.605854  -2.824849     -0.355582   
V25  113842.0  1.680154e-03      0.520069 -10.295397     -0.315470   
V26  113842.0 -2.933701e-04      0.480979  -1.855355     -0.326160   
V27  113842.0 -2.337128e-04      0.399505  -9.895244     -0.070847   
V28  113842.0 -5.080546e-04      0.356130  -9.617915     -0.053249   
V29  113842.0  9.272530e-01      3.412933  -0.307413     -0.230560   
V30  113842.0  1.162315e-01      0.558161  -0.994972     -0.360304   

               50%            75%            max  
ID   141722.000000  213359.500000  284803.000000  
V1        0.012074       1.315373       2.454930  
V2        0.066390       0.801687      21.467203  
V3        0.183868       1.037120       4.187811  
V4       -0.019359       0.742208      16.491217  
V5       -0.054060       0.614214      34.801666  
V6       -0.272436       0.405285      23.917837  
V7        0.039036       0.568750      44.054461  
V8        0.020970       0.328303      20.007208  
V9       -0.052157       0.590705      10.392889  
V10      -0.090810       0.455287      15.331742  
V11      -0.034405       0.739737      10.446847  
V12       0.141434       0.619635       4.318071  
V13      -0.010847       0.663362       4.569009  
V14       0.052157       0.494116       7.518403  
V15       0.048524       0.646540       5.784514  
V16       0.066434       0.525120       8.289890  
V17      -0.066939       0.397480       9.253526  
V18      -0.004633       0.500335       4.295648  
V19       0.004657       0.461655       4.715142  
V20      -0.062891       0.133381      26.237391  
V21      -0.030281       0.186001      27.202839  
V22       0.008346       0.528751       8.361985  
V23      -0.012261       0.147474      22.528412  
V24       0.040573       0.438225       4.022866  
V25       0.018278       0.353989       7.519589  
V26      -0.052815       0.240838       3.119295  
V27       0.001502       0.091279      11.135740  
V28       0.011158       0.077851      33.847808  
V29      -0.000699       0.768532     180.101027  
V30      -0.002590       0.640653       1.034951

In [4]:
# from sklearn.preprocessing import RobustScaler, StandardScaler, MinMaxScaler
# col=[col for col in val_df.columns if col not in ['ID','Class']]

# for i in col:
#     sc=StandardScaler()
#     train_df[i]=sc.fit_transform(train_df[i].values.reshape(-1,1))

In [5]:
import scipy.stats

In [6]:
scipy.stats.norm(0, 1).pdf(3)

0.0044318484119380075

In [7]:
# scipy.stats.norm(0, 1).cdf(0)

In [8]:
# des.loc[0, 'mean']

In [9]:
des = train_df.describe().T
gaussian_model = []
for i in range(1, 31) :
    index = 'V' + str(i)
    gaussian_model.append([des.loc[index, 'mean'], des.loc[index, 'std']])

In [24]:
gaussian_model[0][0]

0.00019729098661136333

In [11]:
val_df.head()

ID        V1        V2        V3        V4        V5        V6        V7  \
0  10 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761  0.651583   
1  22  0.962496  0.328461 -0.171479  2.109204  1.129566  1.696038  0.107712   
2  63  1.145524  0.575068  0.194008  2.598192 -0.092210 -1.044430  0.531588   
3  69  0.927060 -0.323684  0.387585  0.544474  0.246787  1.650358 -0.427576   
4  83 -3.005237  2.600138  1.483691 -2.418473  0.306326 -0.824575  2.065426   

         V8        V9  ...       V22       V23       V24       V25       V26  \
0  0.069539 -0.736727  ... -0.633753 -0.120794 -0.385050 -0.069733  0.094199   
1  0.521502 -1.191311  ...  0.402492 -0.048508 -1.371866  0.390814  0.199964   
2 -0.241888 -0.896287  ... -0.119703 -0.076510  0.691320  0.633984  0.048741   
3  0.615371  0.226278  ...  0.079359  0.096632 -0.992569  0.085096  0.377447   
4 -1.829347  4.009259  ... -0.181268 -0.163747  0.515821  0.136318  0.460054   

        V27       V28       V29       V30  Class  
0  0.246219  0.083076 -0.255991 -0.994878      0  
1  0.016371 -0.014605  0.168937 -0.994784      0  
2 -0.053192  0.016251  0.169496 -0.994502      0  
3  0.036096 -0.005960  0.331307 -0.994467      0  
4 -0.251259 -1.105751 -0.287012 -0.994373      0  

[5 rows x 32 columns]

In [25]:

col=[col for col in val_df.columns if col not in ['ID','Class']]
val_prob = pd.DataFrame(columns=val_df.columns)

for i, v in enumerate(col):
    val_prob[v] = val_df[v].apply(lambda x : scipy.stats.norm(gaussian_model[i][0], gaussian_model[i][1]).pdf(x))


In [26]:
val_prob.head()

ID        V1        V2        V3        V4        V5        V6        V7  \
0  NaN  0.201421  0.192099  0.209881  0.279067  0.272944  0.294500  0.286932   
1  NaN  0.181057  0.236930  0.264564  0.092229  0.207466  0.133719  0.330132   
2  NaN  0.172112  0.227468  0.264497  0.051754  0.291055  0.219663  0.301186   
3  NaN  0.182656  0.236992  0.258152  0.261894  0.287030  0.139600  0.310541   
4  NaN  0.062428  0.070006  0.164123  0.065555  0.284518  0.246849  0.076718   

         V8        V9  ...       V22       V23       V24       V25       V26  \
0  0.335897  0.290851  ...  0.375672  0.616240  0.538559  0.759896  0.813586   
1  0.305204  0.202026  ...  0.472206  0.625484  0.050886  0.579800  0.760575   
2  0.329723  0.260999  ...  0.543670  0.622840  0.342835  0.366324  0.825140   
3  0.293786  0.356363  ...  0.547853  0.619815  0.172486  0.757290  0.609327   
4  0.102644  0.000446  ...  0.534141  0.607087  0.457718  0.741814  0.524646   

        V27       V28       V29       V30  Class  
0  0.825562  1.089784  0.110073  0.098549    NaN  
1  0.997728  1.119339  0.114041  0.098582    NaN  
2  0.989855  1.118977  0.114045  0.098682    NaN  
3  0.994470  1.120085  0.115123  0.098694    NaN  
4  0.819701  0.009074  0.109722  0.098727    NaN  

[5 rows x 32 columns]

In [28]:
val_prob['ID'] = val_df['ID'].values
val_prob['Class'] = val_df['Class'].values
val_prob.head()

ID        V1        V2        V3        V4        V5        V6        V7  \
0  10  0.201421  0.192099  0.209881  0.279067  0.272944  0.294500  0.286932   
1  22  0.181057  0.236930  0.264564  0.092229  0.207466  0.133719  0.330132   
2  63  0.172112  0.227468  0.264497  0.051754  0.291055  0.219663  0.301186   
3  69  0.182656  0.236992  0.258152  0.261894  0.287030  0.139600  0.310541   
4  83  0.062428  0.070006  0.164123  0.065555  0.284518  0.246849  0.076718   

         V8        V9  ...       V22       V23       V24       V25       V26  \
0  0.335897  0.290851  ...  0.375672  0.616240  0.538559  0.759896  0.813586   
1  0.305204  0.202026  ...  0.472206  0.625484  0.050886  0.579800  0.760575   
2  0.329723  0.260999  ...  0.543670  0.622840  0.342835  0.366324  0.825140   
3  0.293786  0.356363  ...  0.547853  0.619815  0.172486  0.757290  0.609327   
4  0.102644  0.000446  ...  0.534141  0.607087  0.457718  0.741814  0.524646   

        V27       V28       V29       V30  Class  
0  0.825562  1.089784  0.110073  0.098549      0  
1  0.997728  1.119339  0.114041  0.098582      0  
2  0.989855  1.118977  0.114045  0.098682      0  
3  0.994470  1.120085  0.115123  0.098694      0  
4  0.819701  0.009074  0.109722  0.098727      0  

[5 rows x 32 columns]

In [47]:
import numpy as np

def geo_mean_overflow(iterable):
    # print(iterable)
    return np.log(np.exp(iterable).mean())

In [48]:
val_prob['prob'] = val_prob.apply(lambda x : geo_mean_overflow(x[1:-1]), axis=1)

In [49]:
val_prob.head()

ID        V1        V2        V3        V4        V5        V6        V7  \
0  10  0.201421  0.192099  0.209881  0.279067  0.272944  0.294500  0.286932   
1  22  0.181057  0.236930  0.264564  0.092229  0.207466  0.133719  0.330132   
2  63  0.172112  0.227468  0.264497  0.051754  0.291055  0.219663  0.301186   
3  69  0.182656  0.236992  0.258152  0.261894  0.287030  0.139600  0.310541   
4  83  0.062428  0.070006  0.164123  0.065555  0.284518  0.246849  0.076718   

         V8        V9  ...       V23       V24       V25       V26       V27  \
0  0.335897  0.290851  ...  0.616240  0.538559  0.759896  0.813586  0.825562   
1  0.305204  0.202026  ...  0.625484  0.050886  0.579800  0.760575  0.997728   
2  0.329723  0.260999  ...  0.622840  0.342835  0.366324  0.825140  0.989855   
3  0.293786  0.356363  ...  0.619815  0.172486  0.757290  0.609327  0.994470   
4  0.102644  0.000446  ...  0.607087  0.457718  0.741814  0.524646  0.819701   

        V28       V29       V30  Class      prob  
0  1.089784  0.110073  0.098549      0  0.418772  
1  1.119339  0.114041  0.098582      0  0.371123  
2  1.118977  0.114045  0.098682      0  0.407762  
3  1.120085  0.115123  0.098694      0  0.385949  
4  0.009074  0.109722  0.098727      0  0.274235  

[5 rows x 33 columns]

In [50]:
# np.log(np.exp(val_prob.iloc[0, :][1:-1].values).mean())

In [70]:
import torch
topk_indices = torch.topk(torch.tensor(val_prob['prob'].values), k=100, largest=False).indices

In [71]:
pred_y = np.zeros(len(val_prob))
pred_y[topk_indices] = 1

In [72]:
np.where(pred_y != val_prob['Class'].values)

(array([   71,   257,   496,   641,   677,   696,  1047,  1210,  1325,
         1798,  2447,  2512,  3055,  3078,  3132,  3197,  3264,  3508,
         3822,  4039,  4851,  4917,  5066,  5384,  5637,  5675,  6273,
         6350,  6896,  6998,  7000,  7211,  7278,  7624,  7630,  7659,
         7702,  7890,  8946,  9326,  9496,  9810, 10066, 10781, 11057,
        11147, 11359, 12256, 12290, 12377, 12505, 12797, 13611, 13706,
        13749, 14221, 15027, 15029, 15030, 15425, 15531, 16346, 16521,
        16812, 16813, 16818, 16903, 16913, 16968, 17290, 17534, 17676,
        18121, 18420, 18580, 18921, 18945, 19036, 19075, 19150, 19203,
        19380, 19620, 19960, 20152, 20336, 20838, 21318, 21429, 21657,
        21825, 21895, 22374, 22545, 22745, 22812, 23050, 23066, 23661,
        24110, 24358, 24742, 25042, 25496, 25504, 26010, 26849, 27159,
        27905, 27998, 28146, 28233, 28274, 28322]),)

In [73]:
from sklearn.metrics import f1_score, confusion_matrix, classification_report

In [74]:
val_score = f1_score(val_prob['Class'].values, pred_y, average='macro')
val_score

0.5605348343947492

In [75]:
val_prob['Class'].values

array([0, 0, 0, ..., 0, 0, 0])

In [76]:
print(classification_report(val_prob['Class'].values, pred_y))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     28432
           1       0.08      0.27      0.12        30

    accuracy                           1.00     28462
   macro avg       0.54      0.63      0.56     28462
weighted avg       1.00      1.00      1.00     28462



In [77]:
confusion_matrix(val_prob['Class'].values, pred_y)

array([[28340,    92],
       [   22,     8]])